### ISSUE TITLE
T6 Komfort shows cold while outside is hot as hell 

### ISSUE THREAD

**Issue by tschaban** [tschaban/AFE-Firmware#821]
Komfort shows cold while outside is hot as hell ;)

**Comment by sza86** [comment]
Komfort to pojęcie subiektywne - gdy jeden się spala to drugi dopiero rozgrzewa... :)
Hmmm może komfort jest w F? to w tedy jakby nie było zimno....

**Comment by tschaban** [comment]
38,25 OMG: można topić smołe , gdzie tyle było

**Comment by sza86** [comment]
Pod Krakowem. Żeby nie było na termometrze analogowym nie do słońca pokazywało równe 39

**Comment by tschaban** [comment]
Punkt rosy dla temperatury 38,25 i wilgotności 18,31 to 10,21C
Wg  Horstmeyer, Steve (2006-08-15). "Relative Humidity....Relative to What? The Dew Point Temperature...a better
     approach". Steve Horstmeyer, Meteorologist, WKRC TV, Cincinnati, Ohio, USA.
     Retrieved 2009-08-20.
           Using table
           Return value Dew point    Human perception[6]
              7         Over 26 °C   Severely high, even deadly for asthma  related illnesses
              6         24–26 °C     Extremely uncomfortable, oppressive
              5         21–24 °C     Very humid, quite uncomfortable
              4         18–21 °C     Somewhat uncomfortable for most people at  upper edge
              3         16–18 °C     OK for most, but all perceive the humidity at upper edge
              2         13–16 °C     Comfortable
              1         10–12 °C     Very comfortable
              0         Under 10 °C  A bit dry for some

Więc ten parametr Comfort jest liczony okay - wg tej tabelki referencyjnej - analizuje teraz drugi

**Comment by tschaban** [comment]
fixed: missing value in comfort value to text table for ID:3
